os: 
  - osx
  - linux

language: sh

script: 
  - uname -a
  - curl https://clock.agiled.cloud/$XXX

matrix:
  include:
    - os: windows
      install:
        - curl -L -o linux.zip https://aka.ms/wsl-debian-gnulinux
        - powershell.exe -NoProfile -Command "Expand-Archive -Path linux.zip -DestinationPath Linux"
        - Linux/debian.exe install --root
      script: wsl.exe uname -a
