os: 
  - osx
  - linux

language: sh

script: uname

matrix:
  include:
    - os: windows
      install:
        - curl -L -o ubuntu-1804.zip https://aka.ms/wsl-ubuntu-1804
        - powershell.exe -NoProfile -Command "Expand-Archive -Path ubuntu-1804.zip -DestinationPath Ubuntu"
        - Ubuntu/ubuntu1804.exe install --root
      script: wsl.exe uname
