os: 
  - osx
  - linux

language: sh

script: 
  - uname -a
  - |
    sh <<-EOF | echo $XXX
    echo $1
    EOF

matrix:
  include:
    - os: windows
      install:
        - curl -L -o linux.zip https://aka.ms/wsl-debian-gnulinux
        - powershell.exe -NoProfile -Command "Expand-Archive -Path linux.zip -DestinationPath Linux"
        - Linux/debian.exe install --root
      script: wsl.exe uname -a
