os: linux
dist: xenial

addons:
  postgresql: "10.7"
  
before_install:
  - sudo /etc/init.d/postgresql stop;
  - sudo /etc/init.d/postgresql start 10;
  - sleep 3
  - psql -c 'SHOW server_version;' -U postgres;

script:
  - netstat -tln
